service: signedUrlDemo

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - s3:PutObject
        - s3:GetObject
      Resource: !Join ["/", [!GetAtt privateUploadsBucket.Arn, "*"]]

functions:
  getS3PreSignedUrl:
    handler: handler.getS3PreSignedUrl
    environment:
      BUCKET_NAME: !Ref privateUploadsBucket
    events:
      - http:
          path: util/getS3PreSignedUrl
          method: post

resources:
  Resources:
    privateUploadsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: !Join ["-", ["youtube-demo-private-uploads", "${self:provider.stage}"]]
        PublicAccessBlockConfiguration:
          BlockPublicAcls: TRUE
          BlockPublicPolicy: TRUE
          IgnorePublicAcls: TRUE
          RestrictPublicBuckets: TRUE
